name: gtk_flutter
description: Get to know Firebase with Flutter
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.7 #The cloud_firestore enables access to Cloud Firestore data storage.
  firebase_auth: ^3.3.6 #The firebase_auth enables integration with Firebase's Authentication capability.
  firebase_core: ^1.12.0 #The firebase_core is the common code required for all Firebase Flutter plugins.
  flutter:
    sdk: flutter
  google_fonts: ^2.1.0
  provider: ^6.0.2 #package that will enable separation of business logic from display logic.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/codelab.png
